# Generated by Django 5.2.1 on 2025-05-31 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_logincoderequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logincoderequest",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
