# Generated by Django 5.2.1 on 2025-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_logincoderequest_requested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cookies",
            field=models.BooleanField(default=False, verbose_name="cookies accepted"),
        ),
    ]
