# Generated by Django 5.2.1 on 2025-06-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_cookies"),
        ("users", "0004_userprofile"),
    ]

    operations = []
