# Generated by Django 5.2.1 on 2025-06-20 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_0004_user_cookies_0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cookies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last time a reminder was sent', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reminder_time',
            field=models.CharField(default='18:00', help_text='Time for daily practice reminders (HH:MM) in UTC', max_length=5),
        ),
        migrations.CreateModel(
            name='PushNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification Subscription',
                'verbose_name_plural': 'Push Notification Subscriptions',
            },
        ),
    ]
