# Generated by Django 5.2.1 on 2025-06-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_cookies_userprofile_reminder_sent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PushNotificationSubscription",
        ),
    ]
