# Generated by Django 5.2.1 on 2025-06-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_pushnotificationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pushover_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
