# Generated by Django 5.2.1 on 2025-06-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_pushover_key_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone for reminders", max_length=50),
        ),
    ]
