# Generated by Django 5.0.9 on 2024-12-08 19:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

from notes.models import Note, Instrument


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1)),
                ('alter', models.IntegerField(choices=[(1, 'Sharp'), (0, 'Natural'), (-1, 'Flat')], default=0)),
                ('octave', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='LearningScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('instrument', models.CharField(blank=True, max_length=64, null=True)),
                ('clef', models.CharField(choices=[('Treble', 'Treble'), ('Tenor', 'Tenor'), ('Alto', 'Alto'), ('Bass', 'Bass')], default='Treble', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ManyToManyField(to='notes.note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=64)),
                ('clef', models.CharField(choices=[('Treble', 'Treble'), ('Tenor', 'Tenor'), ('Alto', 'Alto'), ('Bass', 'Bass')], default='Treble', max_length=64)),
                ('highest_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_highest_note', to='notes.note')),
                ('lowest_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_lowest_note', to='notes.note')),
            ],
        ),
        migrations.CreateModel(
            name='NoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reaction_time', models.PositiveIntegerField(blank=True, null=True)),
                ('n', models.PositiveIntegerField(default=0)),
                ('learning_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.learningscenario')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(Note.create_default_notes),
        migrations.RunPython(Instrument.create_default_instruments),

    ]
