# Generated by Django 5.1.4 on 2025-01-05 14:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=64)),
                ('clef', models.CharField(choices=[('Treble', 'Treble'), ('Tenor', 'Tenor'), ('Alto', 'Alto'), ('Bass', 'Bass')], default='Treble', max_length=64)),
                ('notes_str', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1)),
                ('alter', models.IntegerField(choices=[(1, 'Sharp'), (0, 'Natural'), (-1, 'Flat')], default=0)),
                ('octave', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='LearningScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('clef', models.CharField(choices=[('Treble', 'Treble'), ('Tenor', 'Tenor'), ('Alto', 'Alto'), ('Bass', 'Bass')], default='Treble', max_length=64)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ManyToManyField(to='notes.note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='highest_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_highest_note', to='notes.note'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='lowest_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_lowest_note', to='notes.note'),
        ),
        migrations.CreateModel(
            name='NoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reaction_time', models.PositiveIntegerField(blank=True, null=True)),
                ('n', models.PositiveIntegerField(default=0)),
                ('learningscenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.learningscenario')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteRecordPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('log_minimal', models.TextField(blank=True, null=True)),
                ('log', models.JSONField(blank=True, null=True)),
                ('learningscenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.learningscenario')),
                ('noterecords', models.ManyToManyField(to='notes.noterecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
