# Generated by Django 5.1.4 on 2025-01-19 12:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=64)),
                ('clef', models.CharField(choices=[('Treble', 'Treble'), ('Tenor', 'Tenor'), ('Alto', 'Alto'), ('Bass', 'Bass')], default='Treble', max_length=64)),
                ('lowest_note', models.CharField(blank=True, max_length=20)),
                ('highest_note', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='LearningScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notes', models.JSONField(blank=True, null=True)),
                ('clef', models.CharField(choices=[('Treble', 'Treble'), ('Tenor', 'Tenor'), ('Alto', 'Alto'), ('Bass', 'Bass')], default='Treble', max_length=64)),
                ('key', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='C', max_length=2)),
                ('transposing_direction', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteRecordPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('log', models.JSONField(blank=True, null=True)),
                ('learningscenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.learningscenario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
