# Generated by Django 5.1.4 on 2025-01-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningscenario',
            name='instrument_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='learningscenario',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=64),
        ),
        migrations.AlterField(
            model_name='learningscenario',
            name='key',
            field=models.CharField(choices=[('A', 'A'), ('A#', 'A#'), ('Ab', 'Ab'), ('B', 'B'), ('Bb', 'Bb'), ('C', 'C'), ('C#', 'C#'), ('D', 'D'), ('D#', 'D#'), ('Db', 'Db'), ('E', 'E'), ('Eb', 'Eb'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('G#', 'G#'), ('Gb', 'Gb')], default='C', max_length=2),
        ),
    ]
