# Generated by Django 5.2.1 on 2025-06-13 12:15

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('note', models.CharField(max_length=1)),
                ('alter', models.CharField(blank=True, max_length=2)),
                ('octave', models.CharField(max_length=1)),
                ('reaction_time', models.IntegerField()),
                ('correct', models.BooleanField()),
                ('learningscenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.learningscenario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
