# Generated by Django 5.2.1 on 2025-06-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_noterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningscenario',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningscenario',
            name='reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningscenario',
            name='reminder_type',
            field=models.CharField(blank=True, choices=[('AL', 'All notifications'), ('EM', 'Email only'), ('PN', 'Push notification only'), ('NO', 'No notifications')], default='NO', max_length=2, null=True),
        ),
    ]
