# Generated by Django 5.1.4 on 2025-01-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_learningscenario_instrument_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningscenario',
            name='instrument',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
