# Generated by Django 5.1.4 on 2025-01-13 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_learningscenario_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningscenario',
            name='transposing_direction',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
