# Generated by Django 5.1.4 on 2025-02-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_learningscenario_instrument_delete_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningscenario',
            name='ux',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
