# Generated by Django 5.1.4 on 2025-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_learningscenario_ux'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningscenario',
            name='transpose_key',
            field=models.CharField(choices=[('BL', 'None'), ('A', 'A'), ('A#', 'A#'), ('Ab', 'Ab'), ('B', 'B'), ('Bb', 'Bb'), ('C', 'C'), ('C#', 'C#'), ('D', 'D'), ('D#', 'D#'), ('Db', 'Db'), ('E', 'E'), ('Eb', 'Eb'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('G#', 'G#'), ('Gb', 'Gb')], default='BL', help_text='le', max_length=2),
        ),
    ]
