# Generated by Django 5.2.3 on 2025-06-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_learningscenario_reminder_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningscenario",
            name="reminder_sent",
        ),
    ]
