# Generated by Django 5.2.3 on 2025-07-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_remove_learningscenario_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningscenario",
            name="octave_shift",
            field=models.SmallIntegerField(
                default=0,
                help_text="This is an advanced option. Leave as 0 if unsure. To shift the octave down one, specify -1. To shift up one, specify 1.",
            ),
        ),
    ]
