# Generated by Django 5.2.3 on 2025-09-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_rename_learningscenario_keys"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learningscenario",
            old_name="absolute_key",
            new_name="absolute_pitch",
        ),
    ]
