# Generated by Django 5.2.7 on 2025-10-07 09:45

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_rename_absolute_key_learningscenario_absolute_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningscenario',
            name='signatures',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of integers in [-7..7] – number of sharps (+) or flats (−).', validators=[notes.models.validate_signatures_array]),
        ),
    ]
