# Generated by Django 5.2.6 on 2025-10-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0010_learningscenario_signatures"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NoteRecord",
        ),
    ]
