name: CI

# Enable Buildkit and set up environment variables for optimization
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']
  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  unittest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    env:
      DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/postgres'

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Create Virtual Environment & Install Dependencies
        run: |
          python -m pip install uv
          uv venv --native-tls
          source .venv/bin/activate
          uv pip install -r requirements/local.txt

      - name: Check DB Migrations
        run: |
          source .venv/bin/activate
          python manage.py makemigrations --check
        env:
          DJANGO_SETTINGS_MODULE: config.settings.test

      - name: Apply DB Migrations
        run: |
          source .venv/bin/activate
          python manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: config.settings.test

      - name: Run Python Unit Tests (pytest)
        run: |
          source .venv/bin/activate
          pytest -q
        env:
          DJANGO_SETTINGS_MODULE: config.settings.test

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run JavaScript Tests
        run: npm test
